name: Publish to crates.io

on:
  push:
    tags:
      - 'v0.9.6' 

jobs:
  publish:
    name: Publish Rust crate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable 
          components: rust-src 

      - name: Build and test (optional but recommended)
        run: cargo build --verbose && cargo test --verbose

      - name: Publish to crates.io
        uses: actions-rust-lang/cargo-publish@v1
        with:
          token: ${{ secrets.CRATES_IO_TOKEN }}
          # args: --allow-dirty
